services:
  db:
    image: postgres:16-alpine
    container_name: m2-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: management_system
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
